version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${NAME_DB}
    ports:
      - '5001:5432'
    container_name: taskdb
    volumes: 
      - ./postgresql:/var/lib/postgresql/data
